name: DevOps CI/CD Pipeline

on:
  push:
    branches:
      - ITB703

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -r django_app/requirements.txt
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/Dockerfile.web
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/devops-app:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/devops-app:latest
    
    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible
    
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.MANAGER_IP }} >> ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.WORKER_A_IP }} >> ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.WORKER_B_IP }} >> ~/.ssh/known_hosts
    
    - name: Update inventory with IPs
      run: |
        cd ansible
        sed -i "s/MANAGER_IP/${{ secrets.MANAGER_IP }}/" inventory
        sed -i "s/WORKER_A_IP/${{ secrets.WORKER_A_IP }}/" inventory
        sed -i "s/WORKER_B_IP/${{ secrets.WORKER_B_IP }}/" inventory
        sed -i "s|../terraform/terraform-key.pem|~/.ssh/id_rsa|" inventory
    
    - name: Deploy to Docker Swarm
      run: |
        export ANSIBLE_HOST_KEY_CHECKING=False
        cd ansible
        ansible-playbook -i inventory deploy-stack.yml \
          -e "DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/devops-app:${{ github.sha }}"
    
    - name: Wait for deployment
      run: sleep 30
    
    - name: Install Selenium dependencies
      run: |
        sudo apt-get install -y firefox
        pip install selenium
        wget https://github.com/mozilla/geckodriver/releases/download/v0.33.0/geckodriver-v0.33.0-linux64.tar.gz
        tar -xvzf geckodriver-v0.33.0-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/geckodriver
    
    - name: Run Selenium tests
      run: |
        cd selenium
        sed -i "s/MANAGER_IP/${{ secrets.MANAGER_IP }}/" test_app.py
        python3 test_app.py || true
      continue-on-error: true
    
    - name: Deployment summary
      run: |
        echo "Deployment completed!"
        echo "Application URL: http://${{ secrets.MANAGER_IP }}:8000"
